# docs/es/Makefile

# 1. Path to the main build directory
BUILDDIR      = ../_build

# 2. Include the logic from the parent
include ../Makefile

# 3. Override the source directory to the current folder
# This ensures it builds the Spanish files, not the English ones
SOURCEDIR     = .